version: '3.8'

services:
  solexa-unified:
    build:
      context: .
      dockerfile: Dockerfile.unified
    env_file: .env
    environment:
      - HEADLESS_BROWSER=true
      - DOCKER_ENV=true
      - DOCKER_DEBUG=true
      - LOGLEVEL=DEBUG
      - PYTHONPATH=/app
      - TZ=UTC
      - SKIP_CHMOD=true
      - VERIFICATION_FILE_PATH=/app/static/verifications.json
      - ADMIN_BASE_URL=http://localhost:5000
    ports:
      - "5000:5000"
    volumes:
      - solexa-data:/app/static
      - logs-volume:/app/logs
      - chrome-data:/tmp/chrome_user_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  solexa-data:
  logs-volume:
  chrome-data: 