version: '3.8'

services:
  twitter-bot:
    build:
      context: .
      dockerfile: Dockerfile.twitter
    env_file: .env
    environment:
      - HEADLESS_BROWSER=true
      - DOCKER_ENV=true
      - DOCKER_DEBUG=true
      - LOGLEVEL=DEBUG
      - PYTHONPATH=/app
      - TZ=UTC
      - SKIP_CHMOD=true
      - REMOTE_DEBUGGING_PORT=9222
    volumes:
      - shared-storage:/app/static
      - logs-volume:/app/logs
      - twitter-chrome-data:/app/internal/chrome_data_twitter
    restart: unless-stopped

  web-interface:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: .env
    environment:
      - FLASK_ENV=production
      - DOCKER_ENV=true
      - LOGLEVEL=DEBUG
      - PYTHONPATH=/app
      - TZ=UTC
      - SKIP_CHMOD=true
      - REMOTE_DEBUGGING_PORT=9223
    ports:
      - "5000:5000"
    volumes:
      - shared-storage:/app/static
      - logs-volume:/app/logs
      - web-chrome-data:/app/internal/chrome_data_web
    restart: unless-stopped

volumes:
  shared-storage:
  logs-volume:
  twitter-chrome-data:
  web-chrome-data: 