version: '3.8'

services:
  twitter-bot:
    build:
      context: .
      dockerfile: Dockerfile.twitter
    env_file: .env
    environment:
      - HEADLESS_BROWSER=true
      - DOCKER_ENV=true
      - DOCKER_DEBUG=true
      - LOGLEVEL=DEBUG
      - PYTHONPATH=/app
      - TZ=UTC
      - SKIP_CHMOD=true
    volumes:
      - shared-storage:/app/static
      - logs-volume:/app/logs
    restart: unless-stopped

  web-interface:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: .env
    environment:
      - FLASK_ENV=production
      - DOCKER_ENV=true
      - LOGLEVEL=DEBUG
      - PYTHONPATH=/app
      - TZ=UTC
      - SKIP_CHMOD=true
    ports:
      - "5000:5000"
    volumes:
      - shared-storage:/app/static
      - logs-volume:/app/logs
    restart: unless-stopped

volumes:
  shared-storage:
  logs-volume: 