services:
  - type: web
    name: solexa-unified
    env: docker
    dockerfilePath: Dockerfile.unified
    plan: standard
    numInstances: 1
    envVars:
      - key: HEADLESS_BROWSER
        value: "true"
      - key: DOCKER_ENV
        value: "true"
      - key: LOGLEVEL
        value: "DEBUG"
      - key: DEBUG_STARTUP
        value: "true"
    disk:
      name: solexa-data
      mountPath: /app/static
      sizeGB: 1
    healthCheckPath: /health
  
 