# IMPORTANT: This file should REPLACE all existing content in render.yaml
# Delete everything in render.yaml and replace with this content only

services:
  - type: web
    name: solexa-unified
    env: docker
    dockerfilePath: Dockerfile.unified
    plan: standard
    numInstances: 1
    envVars:
      - key: HEADLESS_BROWSER
        value: "true"
      - key: DOCKER_ENV
        value: "true"
      - key: DOCKER_DEBUG
        value: "true"
      - key: LOGLEVEL
        value: "INFO"
      - key: PYTHONPATH
        value: "/app"
      - key: TZ
        value: "UTC"
      - key: SKIP_CHMOD
        value: "true"
      - key: VERIFICATION_FILE_PATH
        value: "/app/static/verifications.json"
      - key: ADMIN_BASE_URL
        sync: false
      - key: PORT
        value: "5000"
      - key: TWITTER_USERNAME
        sync: false
      - key: TWITTER_PASSWORD
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWITTER_EMAIL
        sync: false
    disk:
      name: solexa-data
      mountPath: /app/static
      sizeGB: 1
    healthCheckPath: /health
  
 